### ISSUE TITLE
Updating, deleting and validating nested associations

### ISSUE THREAD

**Issue by acaron** [apotonick/reform#280]
Handling models marked for destruction and nested associations is not easy to figure out with the current documentation. I've seen similar issues about the `_destroy` property but I ran into another bug.

For example, here is my form class:
```ruby
module Feature
	class TypeForm < Form

		model 'Feature::Type'

		properties :name, :code, :visible_for, :filters

		validates :name, :code, :visible_for, presence: true
		validates :code, numericality: { only_integer: true }

		collection :feature_type_resources, prepopulator: ->(options) { prepopulate_feature_type_resources!(options) } do
			properties :id, :value, :typeable_type, :required, :path_needed
			property :_destroy, virtual: true, writeable: false

			validates :value, presence: true, unless: Proc.new { |f| f._destroy.to_bool }
		end

		def save
			::ActiveRecord::Base.transaction do
				super do |attrs|
					if model.persisted?
						ids_to_remove = attrs['feature_type_resources'].map {|i| i['id'].to_i if i['_destroy'].to_bool }

						self.model.find_feature_type_resource_by_ids(ids_to_remove).destroy_all
						self.feature_type_resources.reject! {|i| ids_to_remove.include? i.id }
					end
				end

				super
			end
		end

	private

		def prepopulate_feature_type_resources!(options)
			self.feature_type_resources << self.model.new_feature_type_resource if self.model.new_record? && self.feature_type_resources.size === 0
		end
	end
end
```

If I add a new resource with a blank value and `_destroy = false`, I get this error: `[Reform] Your :populator did not return a Reform::Form instance for 'feature_type_resources'.` The validation don't pass and the populator is searching for a `fragment[:id]` which doesn't exist yet.

Do you have a way to fix this and simplify the use of the marked as destruction? I know you are working on it. The use case is add and removing resources in one page with the help of JavaScript (like the Cocoon gem does).

**Comment by apotonick** [comment]
In the book, we handle deletion in a `:skip_if` hook in the _Mastering Forms_ chapter. That also explains why populators need to return nested form instances.

I haven't documented deletion, yet, because I think it is wrong to support that on the form level. This is a task very specific to your ORM tier, that's why I left it open and only have examples in the book where I show how this _could_ be done.

Let me know if the example in the book works for you - if you're still having trouble please ask me! :smile:

**Comment by acaron** [comment]
Also, my `:skip_if` argument seems to be ignored. My breakpoint is never triggered with a lambda. Do I need to buy the book to see the examples you talk about? I know there is some examples on your website.

**Comment by apotonick** [comment]
`:skip_if` is only considered in `#validate` - is that where you expect it to kick in?

I know it's a bit messy right now with documentation, apologies for that. My trailblazerb.org website will have all API covered and properly documented one day soon. :wink:  

However, buying the book sounds like a fantastic idea to me!!! :laughing: There's actually two entire chapters about Reform, and looking at your code snippets, I am almost a hundred per cent sure you will like the idea of operations embracing your business code (e.g. what you now do in `#save` in Trailblazer happens in a seperate class called operation. The latter maintains a Reform form object but keeps it a form object by implementing business code separated.)

**Comment by apotonick** [comment]
Oh, and can you paste your form here, again (this time, with `:skip_if`)? I might be able to tell you why it doesn't work, then.

**Comment by acaron** [comment]
I used the code on your don't read section... sorry! :smile: 

So, this is never triggered on new entries (no id set) but it triggers if I do have an id set. Also, `fragment` is set to `"93"`, for example, which is an id... and not an Hash.
```ruby
properties :id, :value, :typeable_type, :required, :path_needed, skip_if: lambda { |fragment, *| fragment['value'].blank? }
```

And this is triggered with a new entry but I receive `""`in my `fragment` variable...
```ruby
property :value, skip_if: lambda { |fragment, *| fragment['value'].blank? }
```

I'm trying to make my Rails application better by separating responsabilities. I added Decorator pattern, your Reform but I kept ActiveRecord instead of Repository pattern. I didn't know about Trailblazer before, but I will look into it!

You do a great job because applying those patterns in Rails is quite hard. I ran into many problems doing so and a lot of questioning about how to do it the best way. I also use a lot the PHP framework Laravel 5 which encourage you to put all form validation in a Form Request, encourage the use of repositories and facades, etc. It makes testing better, maintenance better and application security more easy to manage. I hope Rails will do the same!

**Comment by apotonick** [comment]
Rails won't do anything the like because it will break Basecamp haha! :laughing: 

Trailblazer is exactly what you want: form objects, decorators, view models, representers, business and callback objects, and policies, all separate objects. I really really advise you to check it out: http://devchat.tv/ruby-rogues/206-rr-trailblazer-with-nick-sutterer

`skip_if:` is called per property and retrieves the incoming fragment, e.g. if you set it for a scalar property like `id` the fragment will be the value of `{id: "1", ..}`, in this case `"1"`. Naturally, this is a blank string if the id wasn't set, e.g. for a hash like `{title: "A Thousand Cigarettes"}`.

Again, and sorry to push you, but the book explains `:skip_if` in detail.

**Comment by acaron** [comment]
I see. I thought I was receiving an empty `id` but it is an empty `value`! The documentation is confusing with `fragment['value']`. It should be something like that on `properties` because we can't pinpoint one particular property (we have a value but don't know the owner)!

`skip_if` is working for validation like you said... but I still get the error I first mention. What I actually need is something like this:
```ruby
accepts_nested_attributes_for :posts, reject_if: proc { |attributes| attributes['title'].blank? }
```
See: http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html

I want to totally reject the line if there's no value. Here is a screenshot of my UI:
![screen shot 2015-07-28 at 13 23 48](https://cloud.githubusercontent.com/assets/1609917/8938313/ebc825b6-352b-11e5-9e53-3927cafc8a6a.png)

**Comment by apotonick** [comment]
What if you use `skip_if: :all_blank`?

Are you probably calling `#prepopulate!` before you call `#validate`? This will **always** create another nested form for your `feature_type_resources`, meaning you **always** have an additional form sitting there. If you now hit the `:skip_if` hook when `validate`ing, Reform will skip it (as you said) but not remove it again. 

Do not prepopulate in validate, use `:prepopulate_if_empty` for that. (See book, _Nested Forms_) I consciously designed two different concepts "prepopulator" and "populator" to cover all possible scenarios. All discussed in _Nested Forms_. :wink: 

Haha, sorry but I refuse to read any documentation of `accepts_nested_attributes_for`. :laughing: Not even DHH himself does use it anymore!!!

**Comment by acaron** [comment]
`skip_if: :all_blank` is not really possible when I have checkboxes added... Because it will always be 0 or 1. I use the `prepropulator` attribute so I don't really control when it is called (before or after validate).

I tried `collection :feature_type_resources, populate_if_empty: lambda { |fragment, args| Feature::TypeResource.new }` and `collection :feature_type_resources, prepopulate_if_empty: lambda { |fragment, args| Feature::TypeResource.new }` and both lambdas are never triggered (when I put a breakpoint)...

I checked out your test and this solved my problem: https://github.com/apotonick/reform/blob/master/test/skip_if_test.rb
I must put `skip_if` on `collection`!

```ruby
module Feature
	class TypeForm < Form

		[...]

		collection :feature_type_resources, skip_if: :skip_feature_type_resource?, populate_if_empty: Feature::TypeResource  do
			[...]
		end

		[...]

	private

		def skip_feature_type_resource?(fragment, options)
			fragment['typeable_type'].blank? && fragment['value'].blank?
		end
	end
end
```

So, I only need to make populate if empty work and it will be good! And waiting for a future solution with the destroy thing...

**Comment by acaron** [comment]
I see, if I remove this: `populate_if_empty: Feature::TypeResource` I still get the first error. So it works, but not as I expected. I thought it would show one line with empty fields on the creation form. But it is ok this way!

The documentation is missing some explanation... maybe I can make a pull request with some modifications since the book may not be accessible to some. I will try to buy the book and read it (I use Rails at work so I will have to get the company to buy it).

**Comment by apotonick** [comment]
I think you misunderstand how "prepopulate" works: You have to invoke this directive manually, otherwise your `:prepopulator` option will never be executed. Also, `:prepopulate_if_empty` doesn't exist, haha, where did you read that? :grin: 

I updated the docs: 

http://trailblazerb.org/gems/reform/prepopulator.html
http://trailblazerb.org/gems/reform/populators.html

Please make sure you read _both_ (first few paragraphs will suffice since you're smart), understand the difference between prepopulating and population, check your code if you call `form.prepopulate!` anywhere (if not, your `:prepopulator`s are, ehm, useless) and then come back to me, so we can look into your particular problem. I am pretty sure that you somehow call `prepopulate!` _and_ then call `validate`.

It should be clearer after the new docs - thanks for encouraging me to write them! :smile: If you're still having trouble, maybe we can improve the docs together (after fixing your problem)?

Also: email me if you need a copy, you can buy one later (make sure to use the company credit card).

**Comment by acaron** [comment]
Thanks for your updated documentation! Like I said, it is now doing what I want it to do! I read the first pages available and I really like the structure an ideas of Trailblazer. I will try to buy it today. If I can't, I will ask you for a copy since I'm going on vacation for the next 3 weeks. I still have this important issue: https://github.com/apotonick/reform/issues/270 but the rest is perfect!
